### ISSUE TITLE
Transcript coming back empty

### ISSUE THREAD

**Issue by GavPierce** [ChetanXpro/nodejs-whisper#10]
Transcribing finishes immediately and nothing is returned.
![image](https://github.com/ChetanXpro/nodejs-whisper/assets/75098765/0ab355a9-66c4-4a5d-9fa0-04a296191115)
test.wav is a valid audio file. Yet nothing is coming back?
I have downlowded tiny.en.
What am I missing?

**Comment by ChetanXpro** [comment]
can you see any saved .srt file or .txt file ?

**Comment by pward123** [comment]
Unfortunately, it looks like the embedded cpp application always returns a successful exit code and all output is stderr. So, there's not a good way to detect problems.

If you uncomment [this line](https://github.com/ChetanXpro/nodejs-whisper/blob/d6b97f1a9e148e291ced724ebfee0f642c865e99/src/index.ts#L31) and run your app, you can see the command line that executes the embedded cpp application.

In my case, the command line showed `[Nodejs-whisper]  Executing command: ./main  -otxt -ml 20 -sow true  false  -l auto -m ./models/ggml-large.bin  -f /tmp/foo-vNfStk/audio.wav`

When I ran that command from the `node_modules/nodejs-whisper/cpp/whisper.cpp` folder, I saw the following problematic lines in the output:

```
error: failed to open 'true' as WAV file
error: failed to read WAV file 'true'
error: failed to open 'false' as WAV file
error: failed to read WAV file 'false'
read_wav: WAV file '/tmp/foo-vNfStk/audio.wav' must be 16 kHz
error: failed to read WAV file '/tmp/foo-vNfStk/audio.wav'
```

So, while my file needs to be converted to 16 kHz, the `true false` in the command line generated by the library also seem to be a problem. The `true false` problem is probably [this line](https://github.com/ChetanXpro/nodejs-whisper/blob/d6b97f1a9e148e291ced724ebfee0f642c865e99/src/WhisperHelper.ts#L46) 

I haven't tried to go directly to [the cpp project](https://github.com/ggerganov/whisper.cpp) to see if the exit code issue has been addressed.

**Comment by ChetanXpro** [comment]
sure man , will look into this issue

**Comment by pward123** [comment]
Maybe we can do something like
```
if (stdout.match(/^error:/gm)) {
    throw new Error('whisper.cpp error:\n' + stdout)
```

**Comment by ChetanXpro** [comment]
@GavPierce @pward123 can you once install latest nodejs-whisper version , i made some changes , if you still get any error please let me know,

also i added ffmpeg-static so no need to install ffmpeg in your machine

**Comment by kukadiyaAni** [comment]
I have the latest version but still getting empty with `[Nodejs-whisper] Transcribing Done!`

**Comment by janglewood** [comment]
@kukadiyaAni try to use 16000Hz wav file
