### ISSUE TITLE
How can i get word from hindi or other language audio ?

### ISSUE THREAD

**Issue by dayamangukiya97** [ChetanXpro/nodejs-whisper#101]
Is it possible to get word from hindi audio as well! if yes then how ?

**Comment by SimonRosengren** [comment]
Yes, you'll have to use one of the models not ending in `.en`. 

For example `autoDownloadModelName: 'medium'` . 

If you've already downloaded another model, first go into the cpp-folder under `node_modules/nodejs-whisper/cpp/models` and remove it. This will allow you to auto download the new model

**Comment by dayamangukiya97** [comment]
> Yes, you'll have to use one of the models not ending in `.en`.
> 
> For example `autoDownloadModelName: 'medium'` .
> 
> If you've already downloaded another model, first go into the cpp-folder under `node_modules/nodejs-whisper/cpp/models` and remove it. This will allow you to auto download the new model.
> 
> Whisper can auto detect the language that is spoken, or if you already know what language the audio is, you can provide it in options to make it more efficient.

you mean remove "models" this folder from node-module or remove specific file ?

**Comment by dayamangukiya97** [comment]
<img width="1332" alt="Screenshot 2024-07-31 at 12 50 36 PM" src="https://github.com/user-attachments/assets/f3c83880-4c65-43f0-8201-1da75f1ba47c">

**Comment by dayamangukiya97** [comment]
ok, thanks it works for me!
but i have one more question, i used medium modal and also try other modals for hingi language audio but words not geeting propper accuracy
 i mean to say some hindi word missing, some couple of lines missing, if audio is in female voice then word not getting accurate, last lines missing, and if audio diration blank or music then it throwing innecessory words from hindi audio
 
is there any way to set which type of exact clear audio or something else to solve this problem for get Accurate texts from hindi audio vocal file

Thanks in advance!

here is my code:

const filePath = path.resolve(__dirname, 'DilKaBhawar.mp3');
 await nodewhisper(filePath, {
      modelName: 'medium', // Downloaded model's name
      autoDownloadModelName: 'medium', // (optional) Auto-download a model if the model is not present
      verbose: true,
      removeWavFileAfterTranscription: true,
      withCuda: true, // (optional) Use CUDA for faster processing
      whisperOptions: {
        outputInText: false, // Get output result in a text file
        outputInVtt: false, // Get output result in a VTT file
        outputInSrt: true, // Get output result in an SRT file
        outputInCsv: false, // Get output result in a CSV file
        translateToEnglish: false, // Translate from source language to English
        language: 'hi', // Source language
        timestamps_length: 500, // Amount of dialogue per timestamp pair
        wordTimestamps: true, // Word-level timestamps
        splitOnWord: false, // Split on word rather than on token
      },
    });

**Comment by ChetanXpro** [comment]
@dayamangukiya97 This project is just a wrapper for the whisper cpp project, so for all the performance issues we need to raise issues in the whisper cpp
https://github.com/ggerganov/whisper.cpp
