### ISSUE TITLE
model download feature

### ISSUE THREAD

**Issue by HidanZZ** [ChetanXpro/nodejs-whisper#4]
Hello, could you add a way to download models with a single command line , like this : 
```
npx nodejs-whisper download small.en
``` 

would be very useful .

Thanks a lot.

**Comment by ChetanXpro** [comment]
ohh means you directly want to download model and dont want to see that models list first ?
yup i will add this feature today

**Comment by ChetanXpro** [comment]
hey you can now auto download model , just by passing  autoDownloadModelName: 'base.en' , it will auto download model and will skip if a model already exists

**Comment by binarykitchen** [comment]
Sorry, but it's a bad idea to download the model at runtime. It should happen during npm's `postintall` event.
