### ISSUE TITLE
error when installing with windows 

### ISSUE THREAD

**Issue by LucianoAPP** [ChetanXpro/nodejs-whisper#44]
![image](https://github.com/ChetanXpro/nodejs-whisper/assets/71474960/ad689461-d207-4859-a42a-97aba6314f34)

main.exe -m C:\Developer\Pruebas\whipser-test\node_modules\nodejs-whisper\cpp\whisper.cpp\models\ggml-tiny.bin -f C:\Developer\Pruebas\whipser-test\node_modules\nodejs-whisper\cpp\whisper.cpp\samples\jfk.wav
[Nodejs-whisper] Attempting to compile model...

"cc" no se reconoce como un comando interno o externo,
programa o archivo por lotes ejecutable.
"head" no se reconoce como un comando interno o externo,
programa o archivo por lotes ejecutable.
I whisper.cpp build info:
I UNAME_S:
I UNAME_P:
I UNAME_M:
I CFLAGS:   -I.              -O3 -DNDEBUG -std=c11   -fPIC -D_XOPEN_SOURCE=600 -pthread
I CXXFLAGS: -I. -I./examples -O3 -DNDEBUG -std=c++11 -fPIC -D_XOPEN_SOURCE=600 -pthread
I LDFLAGS:
I CC:
I CXX:

cc  -I.              -O3 -DNDEBUG -std=c11   -fPIC -D_XOPEN_SOURCE=600 -pthread   -c ggml.c -o ggml.o
process_begin: CreateProcess(NULL, uname -s, ...) failed.
process_begin: CreateProcess(NULL, uname -p, ...) failed.
process_begin: CreateProcess(NULL, uname -m, ...) failed.
process_begin: CreateProcess(NULL, which nvcc, ...) failed.
Makefile:299: recipe for target 'ggml.o' failed
process_begin: CreateProcess(NULL, cc -I. -O3 -DNDEBUG -std=c11 -fPIC -D_XOPEN_SOURCE=600 -pthread -c ggml.c -o ggml.o, ...) failed.
make (e=2): El sistema no puede encontrar el archivo especificado.
make: *** [ggml.o] Error 2

**Comment by ChetanXpro** [comment]
It looks like your Windows environment is missing some necessary tools for compiling the code. You'll need to:

1. Install a C compiler, such as GCC. You can get it through MinGW or by installing Cygwin.
2. Ensure that the cc command is in your system PATH.
3. Install Unix-like utilities or use an environment like Git Bash or Windows Subsystem for Linux (WSL) that provides these tools (uname, head, etc.).

**Comment by gabrielmicko** [comment]
Hey @ChetanXpro I might be wrong, but my build seem to be succeeded, but I still always end up in this condition: `if (!shelljs_1.default.which(WHISPER_CPP_MAIN_PATH)) {` which prevents me from running any command.

**Comment by gabrielmicko** [comment]
I think the reason is because WHISPER_CPP_MAIN_PATH is ./main and not ./main.exe therefore .which function will return a wrong result.

**Comment by ChetanXpro** [comment]
> I think the reason is because WHISPER_CPP_MAIN_PATH is ./main and not ./main.exe therefore .which function will return a wrong result.

Thanks @gabrielmicko , i will look into this issue.

**Comment by gabrielmicko** [comment]
Thank you so much. It might be just me, I am not sure. I had a lot of issues creating the `whisper.cpp` build. I would be happy if there was a clear instruction on what to do to run their project on freshly installed windows as I am not really familiar with c++ dev environment. I would also like to create a build that uses Nvida graphics card. In case I succeed I could contribute into adding more docs.

**Comment by ChetanXpro** [comment]
That will be great. When I built this package, I didn't have Windows to test it, so now that I have Windows, I can test it on this platform and fix any bugs.

**Comment by Erarshad** [comment]
how much time doest it take to transcribe 10 min long audio

**Comment by ChetanXpro** [comment]
@Erarshad It depends on how good your CPU is
