### ISSUE TITLE
Add API `autoDownload` feature

### ISSUE THREAD

**Issue by Explosion-Scratch** [ChetanXpro/nodejs-whisper#5]
In options, add `autoDownload` which will auto download the model specified

**Comment by ChetanXpro** [comment]
You can now pass the auto download model name while calling nodejs-whisper, you can check #Usage/Examples in README to know more about usage

need to pass this after modelname parameter
autoDownloadModelName: '<MODELNAME TO DOWNLOAD>'

**Comment by Explosion-Scratch** [comment]
Why not just `autodownload: true`, then use the `model` specified as the model?

**Comment by ChetanXpro** [comment]
ya we can do that as well, i will change it
