### ISSUE TITLE
How can I pass the language flag

### ISSUE THREAD

**Issue by AhabweEmmanuel** [ChetanXpro/nodejs-whisper#83]
Hi thanks for this great library. 

I would like to pass the language for the transcription. Is this option available? I notice the large model tries to automatically detect the language but fails in the process. I would like to pass a language flag to inform whisper which language to use.

**Comment by ChetanXpro** [comment]
Hey, I will add an option to pass the language flag.

**Comment by AhabweEmmanuel** [comment]
Alright, thank you so much.

**Comment by ChetanXpro** [comment]
Added in this commit
https://github.com/ChetanXpro/nodejs-whisper/commit/46fd9aedaae8f9790d2c4e69eae8b1dd2232ec6d
